// Generated by scripts/generate-native-lighting-definitions.py; do not edit.
// Source: revision-274 Server/content/{pack,scripts}; original Java decoder units.
// Reproduce: python3 scripts/generate-native-lighting-definitions.py --server-root /path/to/Server
// SHA256 of sorted relative paths + NUL + exact bytes + NUL for all scanned configs,
// pack ID lists, and the NPC/object/spot-animation packers and Java decoders:
// 3ec25ad0d90e5fd6c92fd034a0df27416487eb40be655e21bc3f59b1f9edbf92
// Nonzero overrides: NPC 1, effects 113, objects 0.
// Offsets only: NPC signed ambient and signed contrast x5; effects unsigned bytes.
import simd

enum NativeDefinitionLighting {
    static func npc(type: Int) -> SIMD2<Int> {
        switch type {
        case 1043: return SIMD2(70, 350)
        default: return .zero
        }
    }
    static func effect(type: Int) -> SIMD2<Int> {
        switch type {
        case 76, 111: return SIMD2(100, 100)
        case 77, 95, 118, 119, 132, 133, 134, 158, 159, 160, 248, 251, 252, 253: return SIMD2(50, 50)
        case 269, 274, 277: return SIMD2(50, 50)
        case 78, 102, 103, 104, 108, 109, 110, 112, 113, 143, 144, 148, 167, 168: return SIMD2(75, 75)
        case 169, 280, 281: return SIMD2(75, 75)
        case 80, 85, 93, 94, 105, 106, 107, 114, 115, 116, 123, 124, 125, 138: return SIMD2(40, 40)
        case 139, 140, 141, 142, 145, 146, 147, 161, 164, 165, 166, 170, 171, 172: return SIMD2(40, 40)
        case 173, 174, 175, 177, 178, 179, 180, 181, 238, 245, 254: return SIMD2(40, 40)
        case 87, 88, 89, 99, 100, 101, 120, 121, 122, 126, 127, 128, 129, 130: return SIMD2(60, 60)
        case 131, 135, 136, 137, 155, 156, 157, 162, 163, 246, 247, 249, 250, 256: return SIMD2(60, 60)
        case 258: return SIMD2(60, 60)
        case 90, 91, 92, 96, 97, 98, 117, 263, 264: return SIMD2(30, 30)
        default: return .zero
        }
    }
}
