#!/usr/bin/env python3
"""Regenerate the small revision-274 lighting fallback from the original server checkout.

NPC source contrast is a signed packed byte decoded as g1b()*5; spot animation
ambient/contrast are unsigned g1 values. Object overrides must remain empty until
an object fallback consumer is implemented. Explicit bridge metadata takes priority.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys

KINDS = ("npc", "obj", "spotanim")
PACKERS = {"npc": "NpcConfig", "obj": "ObjConfig", "spotanim": "SpotAnimConfig"}
CLIENTS = {"npc": "NpcType", "obj": "ObjType", "spotanim": "SpotAnimType"}


def read_pack(path: Path) -> dict[str, int]:
    names: dict[str, int] = {}
    ids: set[int] = set()
    for number, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.split("//", 1)[0].strip()
        if not line:
            continue
        match = re.fullmatch(r"(\d+)=([^=\s]+)", line)
        if not match:
            raise ValueError(f"{path}:{number}: malformed packed ID")
        ident, name = int(match[1]), match[2]
        if ident in ids or name in names:
            raise ValueError(f"{path}:{number}: duplicate packed ID/name")
        ids.add(ident)
        names[name] = ident
    return names


def scan_definitions(paths: list[Path], packed: dict[str, int], kind: str) -> dict[int, tuple[int, int]]:
    definitions: dict[str, dict[str, int]] = {}
    origins: dict[str, str] = {}
    for path in paths:
        current = None
        for number, raw in enumerate(path.read_text().splitlines(), 1):
            line = raw.split("//", 1)[0].strip()
            if not line:
                continue
            if line.startswith("["):
                match = re.fullmatch(r"\[([^\[\]]+)\]", line)
                if not match:
                    raise ValueError(f"{path}:{number}: malformed definition header")
                current = match[1]
                if current in definitions:
                    raise ValueError(f"{path}:{number}: duplicate header {current}; first at {origins[current]}")
                definitions[current] = {}
                origins[current] = f"{path}:{number}"
            else:
                key, separator, value = line.partition("=")
                key = key.strip()
                if key not in ("ambient", "contrast"):
                    continue
                if current is None or not separator or not re.fullmatch(r"[+-]?\d+", value.strip()):
                    raise ValueError(f"{path}:{number}: invalid lighting override")
                if key in definitions[current]:
                    raise ValueError(f"{path}:{number}: duplicate {key} override")
                integer = int(value)
                if not -128 <= integer <= 127:
                    raise ValueError(f"{path}:{number}: lighting override outside signed packed byte")
                definitions[current][key] = integer
    result = {}
    for name, settings in definitions.items():
        if not settings:
            continue
        if name not in packed:
            raise ValueError(f"{origins[name]}: unknown lighting override {name}")
        if kind == "obj":
            raise ValueError(f"{origins[name]}: object lighting override needs a native consumer")
        ambient, contrast = settings.get("ambient", 0), settings.get("contrast", 0)
        pair = (ambient & 255, contrast & 255) if kind == "spotanim" else (ambient, contrast * 5)
        if pair != (0, 0):
            result[packed[name]] = pair
    return result


def generate(server: Path) -> str:
    inputs = []
    tables = {}
    for kind in KINDS:
        pack = server / f"content/pack/{kind}.pack"
        definitions = sorted((server / "content/scripts").rglob(f"*.{kind}"))
        if not definitions:
            raise ValueError(f"No {kind} definitions found")
        inputs.extend([pack, *definitions,
            server / f"engine/tools/pack/config/{PACKERS[kind]}.ts",
            server / f"javaclient/src/main/java/jagex2/config/{CLIENTS[kind]}.java"])
        tables[kind] = scan_definitions(definitions, read_pack(pack), kind)
    digest = hashlib.sha256()
    for path in sorted(inputs):
        digest.update(path.relative_to(server).as_posix().encode() + b"\0" + path.read_bytes() + b"\0")
    lines = [
        "// Generated by scripts/generate-native-lighting-definitions.py; do not edit.",
        "// Source: revision-274 Server/content/{pack,scripts}; original Java decoder units.",
        "// Reproduce: python3 scripts/generate-native-lighting-definitions.py --server-root /path/to/Server",
        "// SHA256 of sorted relative paths + NUL + exact bytes + NUL for all scanned configs,",
        "// pack ID lists, and the NPC/object/spot-animation packers and Java decoders:",
        f"// {digest.hexdigest()}",
        f"// Nonzero overrides: NPC {len(tables['npc'])}, effects {len(tables['spotanim'])}, objects 0.",
        "// Offsets only: NPC signed ambient and signed contrast x5; effects unsigned bytes.",
        "import simd", "", "enum NativeDefinitionLighting {",
    ]
    for api, kind in (("npc", "npc"), ("effect", "spotanim")):
        lines.extend([f"    static func {api}(type: Int) -> SIMD2<Int> {{", "        switch type {"])
        grouped: dict[tuple[int, int], list[int]] = {}
        for ident, pair in sorted(tables[kind].items()):
            grouped.setdefault(pair, []).append(ident)
        for (ambient, contrast), ids in grouped.items():
            # Bound source line length while keeping a compact generated switch.
            for start in range(0, len(ids), 14):
                cases = ", ".join(str(ident) for ident in ids[start:start + 14])
                lines.append(f"        case {cases}: return SIMD2({ambient}, {contrast})")
        lines.extend(["        default: return .zero", "        }", "    }"])
    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--server-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] / "Native/TableScape/Assets/NativeDefinitionLighting.swift")
    parser.add_argument("--check", action="store_true", help="Fail if committed generated output differs")
    args = parser.parse_args()
    try:
        output = generate(args.server_root.resolve())
        if args.check:
            if not args.output.exists() or args.output.read_text() != output:
                raise ValueError(f"Generated lighting definitions are stale: {args.output}")
        else:
            args.output.write_text(output)
        print(f"PASS lighting definitions {'match' if args.check else 'generated'}: {len(output.encode())} bytes")
    except (ValueError, OSError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
